#ifndef LV_CONF_USER_H_
#define LV_CONF_USER_H_

/* Overrides for the lv_conf.h generated by the FSP LVGL pack, which includes this
 * file before its own #ifndef-guarded defaults. */

/* Required: lv_conf_internal.h forces every LV_USE_DEMO_* to 0 without this. */
#define LV_BUILD_DEMOS 1

#define LV_MEM_SIZE (256 * 1024)

#define LV_USE_DRAW_DAVE2D 1
#define LV_USE_RENESAS_GLCDC 1

#define LV_USE_DRAW_SW_COMPLEX_GRADIENTS 1
#define LV_OBJ_STYLE_CACHE 1

#define LV_FONT_MONTSERRAT_24 1

#define LV_USE_SYSMON 1
#define LV_USE_PERF_MONITOR 1
#define LV_USE_MEM_MONITOR 1

/* Defined in LVGL_thread_entry.c; declared here so lv_sysmon.c has a prototype. */
#ifndef __ASSEMBLY__
    #include <stdint.h>
uint32_t get_idle_percent(void);
#endif
#define LV_SYSMON_GET_IDLE get_idle_percent

/* Required for LVGL Pro projects */
#define LV_USE_OBJ_NAME 1
#define LV_USE_TRANSLATION 1

/* LVGL_thread_entry.c prefers the benchmark when both are enabled. */
#define LV_USE_DEMO_WIDGETS 1
#define LV_USE_DEMO_BENCHMARK 1

#endif /* LV_CONF_USER_H_ */
